### ISSUE TITLE
That menu bar.... and the Riverscapes link

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RCAT#9]
Hey @philipbaileynar 

So I noticed that all the riverscapes subdomain sites with the header bar have the menu at the top (see https://github.com/Riverscapes/ConfinementTool/issues/27), are pointing to the current subdomain site instead of to the correct location (i.e. the one below shows on hover over pointing to http://rcat.riverscapes.xyz/# instead of http://www.riverscapes.xyz/

![riverscapes address](https://user-images.githubusercontent.com/9723905/45045132-545afa00-b02f-11e8-9713-cb4b31186d54.png)

## How to fix?
So how do we fix this and do we have to manually do that for all the domains? I suspect you'll say this is in the https://github.com/Riverscapes/RCAT/blob/master/docs/_config.yml file and we have to do it manually for all? Is it something in here:
```
 # ----------------------------------
  topmenu:
    - title: "Riverscapes"
      childern:
        - title: "Model Home"
          url: index
        - title: "Riverscapes Home"
          url: http://riverscapes.xyz

````

Seems like confusion between Model Home and Riverscapes Home?
